### PR TITLE
Make setting the prompt available from ShellServer via a shellHandler.

### PR DESCRIPTION
**Pull request by andrm**
This works now.

    ShellServer server = ShellServer.create(vertx);
    AtomicInteger ai = new AtomicInteger(0);
    server.shellHandler(shell -> {
      shell.setPrompt(s -> {
        try {
          return "C: " + ai.incrementAndGet();
        } catch (Exception e) {
          System.err.println("Counter");
          e.printStackTrace();
        }
        return "NOOP";
      });
    });
    TelnetTermOptions tto = new TelnetTermOptions().setPort(3000).setHost("localhost");
    TermServer telnetTermServer = TermServer.createTelnetTermServer(vertx,tto);
    server.registerTermServer(telnetTermServer);

    server.registerCommandResolver(CommandResolver.baseCommands(vertx));

    server.listen(ar -> {
      if (!ar.succeeded()) {
        ar.cause().printStackTrace();
      }
    });

### CODE REVIEW

**Comment by andrm** [comment]
I'm going to submit an example in vertx-examples also.

**Comment by vietj** [comment]
looks great, can you add a test for this ?

**Comment by andrm** [comment]
Done. I've added this as a close since ShellServerTest had a different initialization.

**Comment by vietj** [comment]
thanks for the contribution!

**Pull request merged**
